services:
  myschool:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: myschool-api
    ports:
      - "8080:8080"
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ASPNETCORE_HTTP_PORTS: 8080
    restart: unless-stopped